Added enumerated value (TURRET_FRAME and title case version) to coord…
pds-data-dictionaries/ldd-geom pull request #28
Opened 2021-07-25 15:52 UTC by mit3ch

…inate_space_frame_type to support Mars2020.

## Summary

Enter summary here

## Test Data and/or Report

Enter info here

## Related Issues

Enter related issues here

2021-07-27 22:26 UTC, jordanpadams requested changes
@mit3ch was the removal of these definitions intentional? it looks to have occurred for a few enumerated values

2021-07-27 22:26 UTC, jordanpadams commented on src/PDS4_GEOM_IngestLDD.xml
> -             <value_meaning>Frame that is attached to the rover and moves with the rover (in both position and orientation). Often synonymous with ROVER_NAV_FRAME.</value_meaning>
@mit3ch was the removal of these definitions intentional? it looks to have occurred for a few enumerated values

2021-07-27 23:28 UTC, thareUSGS commented on src/PDS4_GEOM_IngestLDD.xml
> -             <value_meaning>Frame that is attached to the rover and moves with the rover (in both position and orientation). Often synonymous with ROVER_NAV_FRAME.</value_meaning>
@mit3ch @jordanpadams I noticed that too and kept them in from my quick enumeration updates. I hope that was okay. If not you can dismiss my dev-mkg-002 recent updates and additions. Looks like dev-mkg-002 is building now with "main".

2021-08-03 19:12 UTC, rgdeen commented
Coming to the party late but... I'm not aware of anything that should have been removed... least of all ROVER_FRAME!!  So @thareUSGS thanks for keeping them in, if I interpreted the above properly.

2021-08-03 19:29 UTC, merged